package nsbm.dea.admin.enums;

public enum Status {
  OK,
  BAD_REQUEST,
  INTERNAL_SERVER_ERROR,
  USERNAME_ALREADY_USED,
  EMAIL_ALREADY_USED,
  USERNAME_NOT_VALID,
  EMAIL_NOT_VALID,
  EMAIL_NOT_FOUND,
  WRONG_PASSWORD
}
